language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.x
env:
  - GOOS=windows GOARCH=amd64
  - GOOS=windows GOARCH=386
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=arm
  - GOOS=linux GOARCH=arm64
matrix:
  fast_finish: true
